name: Microservice B Pipeline
on: [workflow_dispatch, workflow_call]

jobs:
  install:
    needs: build_workflow 
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/microservice-b/install

  deploy:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy microservice B"
        run: echo "cdk deploy"
