name: Microservice B - Install
on: [workflow_dispatch, workflow_call]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install Microservice B
        run: echo "Installing microservice B..."
