name: Microservice B Pipeline
on: workflow_dispatch

jobs:
  build_workflow:
    uses: ./.github/workflows/common-build.yml

  install:
    needs: build_workflow
    uses: ./.github/workflows/microservice-b-install.yml

  deploy:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy microservice B"
        run: echo "cdk deploy"
